; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:jumperless_v5]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
framework = arduino
board_build.core = earlephilhower
board_build.filesystem_size = 4m
build_type = debug
extra_scripts =
	pre:scripts/version_from_file.py
	pre:scripts/patch_windows_libs.py
; board_build.f_flash = 150000000L  ; Flash clock 150MHz for faster access
; lib_ldf_mode = deep+
upload_port = /dev/cu.usbmodemJLV5port1
;upload_port = /dev/cu.usbmodem101
board_upload.psram_length = 8388608
build_flags = -Iinclude/
	-Ilib/
	-Imodules/jumperless/
	-Iinclude/
	-Ilib/JDI_MIP_Display/
	-Ilib/micropython/micropython_embed/
	-DUSE_TINYUSB
	-DCFG_TUSB_CONFIG_FILE=\"custom_tusb_config.h\"
	-DCFG_TUD_DESC_AUTO=0
	-DPICO_DEFAULT_UART_TX_PIN=0
	-DPICO_DEFAULT_UART_RX_PIN=1
	-DPICO_ARM=1
	-DRP2350_PSRAM_CS=19
	
	-Wl,--wrap,tud_descriptor_device_cb
	-Wl,--wrap,tud_descriptor_configuration_cb
	-Wl,--wrap,tud_descriptor_string_cb
	-Wl,--wrap,tud_msc_inquiry_cb
	-Wl,--wrap,tud_msc_test_unit_ready_cb
	-Wl,--wrap,tud_msc_capacity_cb
	-Wl,--wrap,tud_msc_start_stop_cb
	-Wl,--wrap,tud_msc_read10_cb
	-Wl,--wrap,tud_msc_write10_cb
	-Wl,--wrap,tud_msc_scsi_cb
	-Wl,--wrap,tud_msc_is_writable_cb
	-Wl,--wrap,tud_cdc_n_connected
	
	-Wl,--allow-multiple-definition
	-Wl,--whole-archive
	-Wl,--no-whole-archive
	-fvisibility=default
	-lm
build_src_filter = +<*> +<../lib/micropython/port/> +<../modules/jumperless/> +<../lib/micropython/micropython_embed/shared/readline/*.c> -<../lib/micropython/micropython_embed/py/> -<../lib/micropython/micropython_embed/extmod/> +<../lib/micropython/micropython_embed/extmod/machine_bitstream.c> +<../lib/micropython/micropython_embed/extmod/machine_adc.c> +<../lib/micropython/micropython_embed/extmod/machine_pwm.c> +<../lib/micropython/micropython_embed/extmod/machine_wdt.c> +<../lib/micropython/micropython_embed/extmod/machine_i2c.c> +<../lib/micropython/micropython_embed/extmod/machine_spi.c> +<../lib/micropython/micropython_embed/extmod/modselect.c> +<../lib/micropython/micropython_embed/extmod/modasyncio.c> +<../lib/micropython/micropython_embed/extmod/moddeflate.c> +<../lib/micropython/micropython_embed/extmod/modframebuf.c> +<../lib/micropython/micropython_embed/extmod/modonewire.c> +<../lib/micropython/micropython_embed/extmod/modjson.c> +<../lib/micropython/micropython_embed/extmod/modre.c> +<../lib/micropython/micropython_embed/extmod/modhashlib.c> +<../lib/micropython/micropython_embed/extmod/modrandom.c> +<../lib/micropython/micropython_embed/extmod/modheapq.c> +<../lib/micropython/micropython_embed/drivers/bus/*.c> -<../lib/micropython/micropython_embed/shared/runtime/> +<../lib/micropython/micropython_embed/shared/timeutils/*.c> -<../lib/micropython/micropython_embed/genhdr/> -<../lib/micropython/micropython_embed/port/> +<../lib/micropython/micropython_embed/port/micropython_embed.c> -<**/Adafruit_USBD_MSC.cpp> -<**/FatFSUSB.cpp> +<../lib/micropython/micropython_embed/shared/runtime/gchelper_generic.c> +<../lib/micropython/micropython_embed/shared/runtime/sys_stdio_mphal.c> +<../lib/micropython/micropython_embed/shared/runtime/mpirq.c>
lib_ignore = FatFSUSB
lib_deps = 
	bblanchon/ArduinoJson
	robtillaart/INA219
	adafruit/Adafruit SSD1306
	adafruit/Adafruit GFX Library
	adafruit/Adafruit TinyUSB Library
	adafruit/Adafruit MCP4728
	adafruit/Adafruit SPIFlash
	adafruit/SdFat - Adafruit Fork
	tobozo/YAMLDuino@^1.5.0
	jostlowe/Pico-DMX@^3.0.1
	powerbroker2/SafeString

board = jumperless_v5



