// Automatically generated by make_root_pointers.py.

const char *readline_hist[(8)];
mp_obj_list_t mp_sys_argv_obj;
mp_obj_t sys_mutable[MP_SYS_MUTABLE_NUM];
mp_sched_item_t sched_queue[(8)];
struct _mp_vfs_mount_t *vfs_cur;
struct _mp_vfs_mount_t *vfs_mount_table;
void *rp2_dma_irq_obj[16];
void *rp2_pio_irq_obj[3];
void *rp2_state_machine_irq_obj[3 * 4];
vstr_t * repl_line;
