#!/usr/bin/env python3
"""
Convert C/C++ style bitmap arrays (from img2cpp, etc.) to raw binary format.

This allows you to use bitmaps generated by tools like:
- img2cpp (https://javl.github.io/image2cpp/)
- image2cpp online tools
- Arduino bitmap converters

Usage:
    python cpp_array_to_bin.py input.h output.bin [--width 128] [--height 32]
"""

import sys
import re
import argparse
from pathlib import Path


def extract_array_from_cpp(file_content):
    """
    Extract bitmap array data from C/C++ header file.
    Supports various formats:
    - const unsigned char array_name[] = { 0x00, 0x01, ... };
    - const uint8_t array_name[] PROGMEM = { 0x00, 0x01, ... };
    - static const unsigned char array_name[] = { ... };
    """
    # Remove comments
    file_content = re.sub(r'//.*?$', '', file_content, flags=re.MULTILINE)
    file_content = re.sub(r'/\*.*?\*/', '', file_content, flags=re.DOTALL)
    
    # Find array declaration
    # Match various C array declarations
    patterns = [
        r'(?:const\s+)?(?:static\s+)?(?:unsigned\s+)?(?:char|uint8_t)\s+\w+\s*\[\s*\]\s*(?:PROGMEM\s*)?=\s*\{([^}]+)\}',
        r'\{([^}]+)\};',  # Just the array itself
    ]
    
    for pattern in patterns:
        match = re.search(pattern, file_content, re.DOTALL)
        if match:
            array_str = match.group(1)
            break
    else:
        return None
    
    # Extract hex values
    hex_values = re.findall(r'0x([0-9A-Fa-f]{2})', array_str)
    
    if not hex_values:
        # Try decimal values
        dec_values = re.findall(r'\b(\d{1,3})\b', array_str)
        return [int(v) for v in dec_values if 0 <= int(v) <= 255]
    
    return [int(v, 16) for v in hex_values]


def array_to_binary(input_path, output_path, width=None, height=None, add_header=False):
    """
    Convert C array to binary file.
    
    Args:
        input_path: Path to C/C++ header file
        output_path: Path to output binary file
        width: Optional width for header
        height: Optional height for header
        add_header: If True, prepend 4-byte header with width/height
    """
    try:
        with open(input_path, 'r', encoding='utf-8', errors='ignore') as f:
            content = f.read()
        
        array_data = extract_array_from_cpp(content)
        
        if not array_data:
            print("Error: Could not find bitmap array in file")
            print("Make sure the file contains a C-style array like:")
            print("  const unsigned char bitmap[] = { 0x00, 0x01, ... };")
            return False
        
        print(f"Found array with {len(array_data)} bytes")
        
        # Try to infer dimensions from data size if not provided
        if not width or not height:
            size = len(array_data)
            if size == 512:
                width, height = 128, 32
                print(f"Auto-detected dimensions: {width}x{height}")
            elif size == 1024:
                width, height = 128, 64
                print(f"Auto-detected dimensions: {width}x{height}")
            elif size == 256:
                width, height = 64, 32
                print(f"Auto-detected dimensions: {width}x{height}")
            elif size == 516:  # 512 + 4 byte header
                width, height = 128, 32
                print(f"Found header in data, dimensions: {width}x{height}")
                array_data = array_data[4:]  # Strip header
                add_header = False  # Don't add another one
            elif width and height:
                expected = (width * height + 7) // 8
                if len(array_data) == expected + 4:
                    print(f"Found header in data, stripping it")
                    array_data = array_data[4:]
                    add_header = False
        
        # Write output file
        with open(output_path, 'wb') as f:
            if add_header and width and height:
                # Write 4-byte header (width, height as 16-bit little-endian)
                f.write(width.to_bytes(2, byteorder='little'))
                f.write(height.to_bytes(2, byteorder='little'))
                print(f"Added 4-byte header: {width}x{height}")
            
            f.write(bytes(array_data))
        
        output_size = len(array_data) + (4 if add_header else 0)
        print(f"Successfully converted to {output_path}")
        print(f"Output size: {output_size} bytes")
        
        if width and height:
            expected = (width * height + 7) // 8
            if len(array_data) == expected:
                print(f"✓ Size matches dimensions {width}x{height}")
            else:
                print(f"⚠ Warning: Size mismatch!")
                print(f"  Expected {expected} bytes for {width}x{height}")
                print(f"  Got {len(array_data)} bytes")
        
        return True
        
    except Exception as e:
        print(f"Error: {e}")
        return False


def main():
    parser = argparse.ArgumentParser(
        description='Convert C/C++ bitmap arrays to binary format',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Convert img2cpp output to raw binary
  python cpp_array_to_bin.py bitmap.h bitmap.bin
  
  # Convert and add custom header with dimensions
  python cpp_array_to_bin.py bitmap.h bitmap.bin --width 128 --height 32 --header
  
  # Convert for Jumperless (auto-detects dimensions)
  python cpp_array_to_bin.py logo.h /logo.bin

Supported input formats:
  - img2cpp output (https://javl.github.io/image2cpp/)
  - Arduino bitmap arrays
  - Any C-style byte array with hex or decimal values
        """
    )
    
    parser.add_argument('input', help='Input C/C++ header file (.h, .cpp)')
    parser.add_argument('output', help='Output binary file (.bin)')
    parser.add_argument('--width', type=int, help='Bitmap width in pixels')
    parser.add_argument('--height', type=int, help='Bitmap height in pixels')
    parser.add_argument('--header', action='store_true',
                       help='Add 4-byte header (width, height) to output')
    
    args = parser.parse_args()
    
    if not Path(args.input).exists():
        print(f"Error: Input file '{args.input}' not found")
        sys.exit(1)
    
    success = array_to_binary(args.input, args.output, args.width, args.height, args.header)
    sys.exit(0 if success else 1)


if __name__ == '__main__':
    main()

