#pragma once

const char* rp2_py_content = 
    "# rp2 module: uses C code from _rp2, plus asm_pio decorator implemented in Python.\n"
    "# MIT license; Copyright (c) 2020-2021 Damien P. George\n"
    "\n"
    "from _rp2 import *\n"
    "from micropython import const\n"
    "\n"
    "_PROG_DATA = const(0)\n"
    "_PROG_OFFSET_PIO0 = const(1)\n"
    "_PROG_OFFSET_PIO1 = const(2)\n"
    "_PROG_EXECCTRL = const(3)\n"
    "_PROG_SHIFTCTRL = const(4)\n"
    "_PROG_OUT_PINS = const(5)\n"
    "_PROG_SET_PINS = const(6)\n"
    "_PROG_SIDESET_PINS = const(7)\n"
    "_PROG_MAX_FIELDS = const(8)\n"
    "\n"
    "\n"
    "class PIOASMError(Exception):\n"
    "    pass\n"
    "\n"
    "\n"
    "class PIOASMEmit:\n"
    "    def __init__(\n"
    "        self,\n"
    "        *,\n"
    "        out_init=None,\n"
    "        set_init=None,\n"
    "        sideset_init=None,\n"
    "        side_pindir=False,\n"
    "        in_shiftdir=PIO.SHIFT_LEFT,\n"
    "        out_shiftdir=PIO.SHIFT_LEFT,\n"
    "        autopush=False,\n"
    "        autopull=False,\n"
    "        push_thresh=32,\n"
    "        pull_thresh=32,\n"
    "        fifo_join=PIO.JOIN_NONE,\n"
    "    ):\n"
    "        # array is a built-in module so importing it here won't require\n"
    "        # scanning the filesystem.\n"
    "        from array import array\n"
    "\n"
    "        self.labels = {}\n"
    "        execctrl = side_pindir << 29\n"
    "        shiftctrl = (\n"
    "            fifo_join << 30\n"
    "            | (pull_thresh & 0x1F) << 25\n"
    "            | (push_thresh & 0x1F) << 20\n"
    "            | out_shiftdir << 19\n"
    "            | in_shiftdir << 18\n"
    "            | autopull << 17\n"
    "            | autopush << 16\n"
    "        )\n"
    "        self.prog = [array(\"H\"), -1, -1, execctrl, shiftctrl, out_init, set_init, sideset_init]\n"
    "\n"
    "        self.wrap_used = False\n"
    "\n"
    "        if sideset_init is None:\n"
    "            self.sideset_count = 0\n"
    "        elif isinstance(sideset_init, int):\n"
    "            self.sideset_count = 1\n"
    "        else:\n"
    "            self.sideset_count = len(sideset_init)\n"
    "\n"
    "    def start_pass(self, pass_):\n"
    "        if pass_ == 1:\n"
    "            if not self.wrap_used and self.num_instr:\n"
    "                self.wrap()\n"
    "            self.delay_max = 31\n"
    "            if self.sideset_count:\n"
    "                self.sideset_opt = self.num_sideset != self.num_instr\n"
    "                if self.sideset_opt:\n"
    "                    self.prog[_PROG_EXECCTRL] |= 1 << 30\n"
    "                    self.sideset_count += 1\n"
    "                self.delay_max >>= self.sideset_count\n"
    "        self.pass_ = pass_\n"
    "        self.num_instr = 0\n"
    "        self.num_sideset = 0\n"
    "\n"
    "    def __getitem__(self, key):\n"
    "        return self.delay(key)\n"
    "\n"
    "    def delay(self, delay):\n"
    "        if self.pass_ > 0:\n"
    "            if delay > self.delay_max:\n"
    "                raise PIOASMError(\"delay too large\")\n"
    "            self.prog[_PROG_DATA][-1] |= delay << 8\n"
    "        return self\n"
    "\n"
    "    def side(self, value):\n"
    "        self.num_sideset += 1\n"
    "        if self.pass_ > 0:\n"
    "            if self.sideset_count == 0:\n"
    "                raise PIOASMError(\"no sideset\")\n"
    "            elif value >= (1 << self.sideset_count):\n"
    "                raise PIOASMError(\"sideset too large\")\n"
    "            set_bit = 13 - self.sideset_count\n"
    "            self.prog[_PROG_DATA][-1] |= self.sideset_opt << 12 | value << set_bit\n"
    "        return self\n"
    "\n"
    "    def wrap_target(self):\n"
    "        self.prog[_PROG_EXECCTRL] |= self.num_instr << 7\n"
    "\n"
    "    def wrap(self):\n"
    "        assert self.num_instr\n"
    "        self.prog[_PROG_EXECCTRL] |= (self.num_instr - 1) << 12\n"
    "        self.wrap_used = True\n"
    "\n"
    "    def label(self, label):\n"
    "        if self.pass_ == 0:\n"
    "            if label in self.labels:\n"
    "                raise PIOASMError(\"duplicate label {}\".format(label))\n"
    "            self.labels[label] = self.num_instr\n"
    "\n"
    "    def word(self, instr, label=None):\n"
    "        self.num_instr += 1\n"
    "        if self.pass_ > 0:\n"
    "            if label is None:\n"
    "                label = 0\n"
    "            else:\n"
    "                if label not in self.labels:\n"
    "                    raise PIOASMError(\"unknown label {}\".format(label))\n"
    "                label = self.labels[label]\n"
    "            self.prog[_PROG_DATA].append(instr | label)\n"
    "        return self\n"
    "\n"
    "    def nop(self):\n"
    "        return self.word(0xA042)\n"
    "\n"
    "    def jmp(self, cond, label=None):\n"
    "        if label is None:\n"
    "            label = cond\n"
    "            cond = 0  # always\n"
    "        return self.word(0x0000 | cond << 5, label)\n"
    "\n"
    "    def wait(self, polarity, src, index):\n"
    "        if src == 6:\n"
    "            src = 1  # \"pin\"\n"
    "        elif src != 0:\n"
    "            src = 2  # \"irq\"\n"
    "        return self.word(0x2000 | polarity << 7 | src << 5 | index)\n"
    "\n"
    "    def in_(self, src, data):\n"
    "        if not 0 < data <= 32:\n"
    "            raise PIOASMError(\"invalid bit count {}\".format(data))\n"
    "        return self.word(0x4000 | src << 5 | data & 0x1F)\n"
    "\n"
    "    def out(self, dest, data):\n"
    "        if dest == 8:\n"
    "            dest = 7  # exec\n"
    "        if not 0 < data <= 32:\n"
    "            raise PIOASMError(\"invalid bit count {}\".format(data))\n"
    "        return self.word(0x6000 | dest << 5 | data & 0x1F)\n"
    "\n"
    "    def push(self, value=0, value2=0):\n"
    "        value |= value2\n"
    "        if not value & 1:\n"
    "            value |= 0x20  # block by default\n"
    "        return self.word(0x8000 | (value & 0x60))\n"
    "\n"
    "    def pull(self, value=0, value2=0):\n"
    "        value |= value2\n"
    "        if not value & 1:\n"
    "            value |= 0x20  # block by default\n"
    "        return self.word(0x8080 | (value & 0x60))\n"
    "\n"
    "    def mov(self, dest, src):\n"
    "        if dest == 8:\n"
    "            dest = 4  # exec\n"
    "        return self.word(0xA000 | dest << 5 | src)\n"
    "\n"
    "    def irq(self, mod, index=None):\n"
    "        if index is None:\n"
    "            index = mod\n"
    "            mod = 0  # no modifiers\n"
    "        return self.word(0xC000 | (mod & 0x60) | index)\n"
    "\n"
    "    def set(self, dest, data):\n"
    "        return self.word(0xE000 | dest << 5 | data)\n"
    "\n"
    "\n"
    "_pio_funcs = {\n"
    "    # source constants for wait\n"
    "    \"gpio\": 0,\n"
    "    # \"pin\": see below, translated to 1\n"
    "    # \"irq\": see below function, translated to 2\n"
    "    # source/dest constants for in_, out, mov, set\n"
    "    \"pins\": 0,\n"
    "    \"x\": 1,\n"
    "    \"y\": 2,\n"
    "    \"null\": 3,\n"
    "    \"pindirs\": 4,\n"
    "    \"pc\": 5,\n"
    "    \"status\": 5,\n"
    "    \"isr\": 6,\n"
    "    \"osr\": 7,\n"
    "    \"exec\": 8,  # translated to 4 for mov, 7 for out\n"
    "    # operation functions for mov's src\n"
    "    \"invert\": lambda x: x | 0x08,\n"
    "    \"reverse\": lambda x: x | 0x10,\n"
    "    # jmp condition constants\n"
    "    \"not_x\": 1,\n"
    "    \"x_dec\": 2,\n"
    "    \"not_y\": 3,\n"
    "    \"y_dec\": 4,\n"
    "    \"x_not_y\": 5,\n"
    "    \"pin\": 6,\n"
    "    \"not_osre\": 7,\n"
    "    # constants for push, pull\n"
    "    \"noblock\": 0x01,\n"
    "    \"block\": 0x21,\n"
    "    \"iffull\": 0x40,\n"
    "    \"ifempty\": 0x40,\n"
    "    # constants and modifiers for irq\n"
    "    # \"noblock\": see above\n"
    "    # \"block\": see above\n"
    "    \"clear\": 0x40,\n"
    "    \"rel\": lambda x: x | 0x10,\n"
    "}\n"
    "\n"
    "\n"
    "_pio_directives = (\n"
    "    \"wrap_target\",\n"
    "    \"wrap\",\n"
    "    \"label\",\n"
    ")\n"
    "\n"
    "\n"
    "_pio_instructions = (\n"
    "    \"word\",\n"
    "    \"nop\",\n"
    "    \"jmp\",\n"
    "    \"wait\",\n"
    "    \"in_\",\n"
    "    \"out\",\n"
    "    \"push\",\n"
    "    \"pull\",\n"
    "    \"mov\",\n"
    "    \"irq\",\n"
    "    \"set\",\n"
    ")\n"
    "\n"
    "\n"
    "def asm_pio(**kw):\n"
    "    emit = PIOASMEmit(**kw)\n"
    "\n"
    "    def dec(f):\n"
    "        nonlocal emit\n"
    "\n"
    "        gl = f.__globals__\n"
    "        old_gl = gl.copy()\n"
    "        gl.clear()\n"
    "\n"
    "        gl.update(_pio_funcs)\n"
    "        for name in _pio_directives:\n"
    "            gl[name] = getattr(emit, name)\n"
    "        for name in _pio_instructions:\n"
    "            gl[name] = getattr(emit, name)\n"
    "\n"
    "        emit.start_pass(0)\n"
    "        f()\n"
    "\n"
    "        emit.start_pass(1)\n"
    "        f()\n"
    "\n"
    "        gl.clear()\n"
    "        gl.update(old_gl)\n"
    "\n"
    "        return emit.prog\n"
    "\n"
    "    return dec\n"
    "\n"
    "\n"
    "# sideset_count is inclusive of enable bit\n"
    "def asm_pio_encode(instr, sideset_count, sideset_opt=False):\n"
    "    emit = PIOASMEmit()\n"
    "    emit.sideset_count = sideset_count\n"
    "    emit.sideset_opt = sideset_opt != 0\n"
    "    emit.delay_max = 31 >> (emit.sideset_count + emit.sideset_opt)\n"
    "    emit.pass_ = 1\n"
    "    emit.num_instr = 0\n"
    "    emit.num_sideset = 0\n"
    "\n"
    "    gl = _pio_funcs\n"
    "    for name in _pio_instructions:\n"
    "        gl[name] = getattr(emit, name)\n"
    "    gl[\"jmp\"] = None  # emit.jmp currently not supported\n"
    "\n"
    "    try:\n"
    "        exec(instr, gl)\n"
    "    finally:\n"
    "        for name in _pio_instructions:\n"
    "            del gl[name]\n"
    "\n"
    "    if len(emit.prog[_PROG_DATA]) != 1:\n"
    "        raise PIOASMError(\"expecting exactly 1 instruction\")\n"
    "    return emit.prog[_PROG_DATA][0]\n"
    "\n"
;
